# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on:
  push:
    branches:
      - main
  pull_request:

env:
  SPACK_REPO: ekarpovi/spack
  SPACK_BRANCH: intel-oneapi-2022.1.1-release

jobs:
  intel-compiler:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [icx]
        part: [1]
        os: [ubuntu-20.04]
    name: ${{ matrix.compiler }}_${{ matrix.part }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
    - name: Install spack
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SPACK_REPO }}
        path: spack
        ref: ${{ env.SPACK_BRANCH }}
    - name: Package tests
      run: |
        source spack/share/spack/setup-env.sh
        spack repo add ./repo
        spack install intel-oneapi-compilers
        spack clean --downloads
        spack compiler add `spack location -i intel-oneapi-compilers`/compiler/latest/linux/bin/intel64
        spack compiler add `spack location -i intel-oneapi-compilers`/compiler/latest/linux/bin
        echo looking for sycl-post-link
        ls `spack location -i intel-oneapi-compilers`/compiler/latest/linux/bin
        echo manual execute
        spack install  --no-checksum --fail-fast oneapi-test-basic%oneapi +sycl
        echo full execute
        pytest -s tests/test_packages.py::test_${{ matrix.compiler }}_${{ matrix.part }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.compiler }}-${{ matrix.part }}-${{ matrix.os }}-logs
        path: |
          /tmp/runner/spack-stage/
          /tmp/runner/intel-oneapi-installer/
          !/tmp/runner/**/*.sh
          bootstrapper*
          installer*
        retention-days: 7
